# Generated by Django 5.1.1 on 2024-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
