# Generated by Django 5.1.1 on 2024-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=500)),
                ('degree', models.CharField(max_length=100)),
                ('income', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
